# Generated by Django 5.0.4 on 2024-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0016_alter_product_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
            ],
        ),
    ]
