# Generated by Django 5.0.4 on 2024-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0017_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
