# Generated by Django 5.0.6 on 2024-07-12 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0019_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
